window.GOLPESWIPE_CONFIG = {
  SUPABASE_URL: 'https://yfsgfzibjnqaayvcdrjz.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmc2dmemliam5xYWF5dmNkcmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwMDY3MDMsImV4cCI6MjA5NTU4MjcwM30.2BGZLNNCurSdcmOOhmcrTFUjIoULJ9RO33raCcCrlnE'
};
